version: '3'
services:
        web:
                build: .
                container_name: du-docker
                env_file: .env
                ports:
                        - "3000:3000"
                links:
                        - "db:mongo"
                volumes:
                        - .:/usr/src/app
                        - node_modules:/usr/src/app/node_modules
                networks:
                        - app-network
                command: yarn run dev
        db:
                image: mvertes/alpine-mongo
                container_name: mongo
                networks:
                        - app-network
networks:
        app-network:
                driver: bridge

volumes:
        node_modules: